#!/bin/bash
if [ $# -lt 2 ]; then
    echo "Usage: demacs path-to-activate-script ..."
    exit 1
fi

source $1
shift

os=$(uname)
args="-nw -q --load $HOME/.demacs/init.el"
if [ $os == "Darwin" ]; then
  /Applications/Emacs.app/Contents/MacOS/Emacs $args $@
else
  emacs $args $@
fi
